- name: Deploy AWS Lambda function
  hosts: localhost

  tasks:
    - archive:
        path: /home/vagrant/deploytoLambda/src/backup-ec2.py
        format: zip
        dest: /home/vagrant/deploytoLambda/src/backup-ec2.zip
    - set_fact: LAMBDA_ARN="YOUR_LAMBDA_ROLE_ARN"
    - set_fact: INSTANCE_ID=""
    - set_fact: INSTANCE_NAME=""
    - set_fact: INSTANCE_DESCRIPTION=""
    - name: Create lambda function
      lambda:
        name: "backup_ec2_via_ansible"
        state: present
        zip_file: /home/vagrant/deploytoLambda/src/backup-ec2.zip
        runtime: 'python2.7'
        role: "{{LAMBDA_ARN}}"
        handler: 'backup-ec2.run_handler'
        description: "Testing Backup of EC2 instance via Ansible"       
        environment_variables:
          instance_id: "{{INSTANCE_ID}}"
          instance_name: "{{INSTANCE_NAME}}"
          instance_description:  "{{INSTANCE_DESCRIPTION}}"     